### ISSUE TITLE
Inconsistent executions in allow-set due to deadness predicate

### ISSUE THREAD

**Issue by nchong** [johnwickerson/memalloy#13]
The following execution is synthesised for the allow-set for Power 6ev. It is inconsistent.

![image001](https://user-images.githubusercontent.com/218049/32889507-1c993516-cac3-11e7-9847-edd39ec87e12.png)

The execution was weakened from the following forbidden execution (by removing event e2). 

![test_258d67088b67ffdf43330d0828e7d33e 1](https://user-images.githubusercontent.com/218049/32889540-40681700-cac3-11e7-9e1d-17b1db49c0cb.png)

Quoting John:

> [...] it's a deadness issue.
> 
> An execution is minimally-interesting if it is interesting and any event-removal leads to an uninteresting execution.
> 
> An execution is interesting if it is inconsistent *and* dead.
> 
> When you remove E2, you get an inconsistent execution, but it's not dead, so it's deemed uninteresting.
> 
> The reason the reduced (i.e. 5-event) execution is *not* dead is because it has a ctrl dependency coming out of a read that observes the initial value. (You don't have this in the original 6-event execution.) Executions that have this pattern are deemed not dead. This, you may recall, was because I had an issue in POPL'17 whereby if I was control dependent on a read of zero, I couldn't tell if the read had successfully seen zero or just not happened yet. I'm no longer convinced that this is actually an issue.

**Comment by nchong** [comment]
We should try to remove this particular constraint on deadness. This will require changes to the generation when we have a control-dependency from a read that reads the initial value 0.

Two possible ways of dealing with this:
- Change the initial value of the destination register (say, -1)
- Change the assignment of the destination register into a ternary:

        rd := rn == 0 ? load(x) : -1

**Comment by johnwickerson** [comment]
I've kept this deadness constraint, but now it only appears in the deadness definition for C++/OpenCL models. Hardware models no longer enforce it.
